"""Initial schema

Revision ID: e6f375b58c9a
Revises: 
Create Date: 2026-01-26 00:20:43.254147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6f375b58c9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('join_link', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_check', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_message_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sources_active', 'sources', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_sources_chat_id'), 'sources', ['chat_id'], unique=True)
    op.create_table('message_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('grouped_id', sa.BigInteger(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('media_file_id', sa.BigInteger(), nullable=True),
    sa.Column('media_access_hash', sa.BigInteger(), nullable=True),
    sa.Column('media_file_reference', sa.LargeBinary(), nullable=True),
    sa.Column('original_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('original_message_id', sa.BigInteger(), nullable=True),
    sa.Column('rewritten_text', sa.Text(), nullable=True),
    sa.Column('rewrite_status', sa.String(length=20), nullable=True),
    sa.Column('rewrite_error', sa.Text(), nullable=True),
    sa.Column('rewritten_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('awaiting_text', sa.Boolean(), nullable=True),
    sa.Column('awaiting_until', sa.TIMESTAMP(), nullable=True),
    sa.Column('linked_message_id', sa.BigInteger(), nullable=True),
    sa.Column('collected_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ready_to_post', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'message_id', name='uq_source_message')
    )
    op.create_index('idx_queue_awaiting', 'message_queue', ['awaiting_text', 'awaiting_until'], unique=False, postgresql_where=sa.text('awaiting_text = true'))
    op.create_index('idx_queue_grouped', 'message_queue', ['grouped_id'], unique=False, postgresql_where=sa.text('grouped_id IS NOT NULL'))
    op.create_index('idx_queue_ready_to_post', 'message_queue', ['ready_to_post'], unique=False, postgresql_where=sa.text('ready_to_post = true'))
    op.create_index('idx_queue_rewrite_pending', 'message_queue', ['rewrite_status'], unique=False, postgresql_where=sa.text("rewrite_status = 'pending'"))
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('grouped_id', sa.BigInteger(), nullable=True),
    sa.Column('original_source_id', sa.BigInteger(), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('posted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('post_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['original_source_id'], ['sources.chat_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_scheduled', 'posts', ['status', 'scheduled_at'], unique=False, postgresql_where=sa.text("status = 'scheduled'"))
    op.create_table('post_media',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('message_queue_id', sa.BigInteger(), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('media_file_id', sa.BigInteger(), nullable=True),
    sa.Column('media_access_hash', sa.BigInteger(), nullable=True),
    sa.Column('media_file_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['message_queue_id'], ['message_queue.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_media_post_id', 'post_media', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_media_post_id', table_name='post_media')
    op.drop_table('post_media')
    op.drop_index('idx_posts_scheduled', table_name='posts', postgresql_where=sa.text("status = 'scheduled'"))
    op.drop_table('posts')
    op.drop_index('idx_queue_rewrite_pending', table_name='message_queue', postgresql_where=sa.text("rewrite_status = 'pending'"))
    op.drop_index('idx_queue_ready_to_post', table_name='message_queue', postgresql_where=sa.text('ready_to_post = true'))
    op.drop_index('idx_queue_grouped', table_name='message_queue', postgresql_where=sa.text('grouped_id IS NOT NULL'))
    op.drop_index('idx_queue_awaiting', table_name='message_queue', postgresql_where=sa.text('awaiting_text = true'))
    op.drop_table('message_queue')
    op.drop_index(op.f('ix_sources_chat_id'), table_name='sources')
    op.drop_index('idx_sources_active', table_name='sources', postgresql_where=sa.text('is_active = true'))
    op.drop_table('sources')
    # ### end Alembic commands ###
